// src/svelte/components/Separator.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { orientation = "horizontal", decorative = true, class: className, ...restProps }: {
  orientation?: "horizontal" | "vertical";
  decorative?: boolean;
    class?: string;
    [key: string]: any;
  } = $props();




let classes = $derived(
cn(
    "shrink-0 bg-[hsl(var(--la-border))]",
    orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]",
    className,
  ),
);
</script>

<div
    :role="decorative ? 'none' : 'separator'"
    :aria-orientation="decorative ? undefined : orientation"
    class={classes}
  / {...restProps}>

// src/components/Separator/Separator.tsx
import * as SeparatorPrimitive from "@radix-ui/react-separator";
import type * as React from "react";
import { cn } from "../../lib/utils";

function Separator({
  className,
  orientation = "horizontal",
  decorative = true,
  ref,
  ...props
}: React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root> & {
  ref?: React.Ref<React.ComponentRef<typeof SeparatorPrimitive.Root>>;
}) {
  return (
    <SeparatorPrimitive.Root
      ref={ref}
      decorative={decorative}
      orientation={orientation}
      className={cn(
        "shrink-0 bg-border",
        orientation === "horizontal" ? "h-px w-full" : "h-full w-px",
        className,
      )}
      {...props}
    />
  );
}
Separator.displayName = SeparatorPrimitive.Root.displayName;

export type SeparatorProps = React.ComponentPropsWithoutRef<
  typeof SeparatorPrimitive.Root
> & { ref?: React.Ref<React.ComponentRef<typeof SeparatorPrimitive.Root>> };

export { Separator };
