// src/svelte/components/Badge.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { variant = "default", class: className, children, ...restProps }: {
  variant?: "default" | "secondary" | "destructive" | "outline";
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();




const variantClasses = {
  default: "border-transparent bg-[hsl(var(--la-primary))] text-[hsl(var(--la-primary-foreground))]",
  secondary: "border-transparent bg-[hsl(var(--la-secondary))] text-[hsl(var(--la-secondary-foreground))]",
  destructive: "border-transparent bg-[hsl(var(--la-destructive))] text-[hsl(var(--la-destructive-foreground))]",
  outline: "text-[hsl(var(--la-foreground))]",
};

let classes = $derived(
cn(
    "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-[hsl(var(--la-ring))] focus:ring-offset-2",
    variantClasses[variant],
    className,
  ),
);
</script>

<div class={classes} {...restProps}>
    {@render children?.()}
  </div>

// src/components/Badge/Badge.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/utils";

const badgeVariants = cva(
  "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      variant: {
        default: "border-transparent bg-primary text-primary-foreground",
        secondary: "border-transparent bg-secondary text-secondary-foreground",
        outline: "border-border text-foreground",
        destructive: "border-transparent bg-destructive text-destructive-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
);

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

/**
 * Badge component. By default, no ARIA role is applied.
 * Pass `role="status"` for live-updating badges (politely announced by screen readers)
 * or `role="alert"` for urgent announcements that require immediate attention.
 */
const Badge = React.forwardRef<HTMLDivElement, BadgeProps>(
  ({ className, variant, ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(badgeVariants({ variant }), className)}
        {...props}
      />
    );
  }
Badge.displayName = "Badge";

export { Badge, badgeVariants };
