// src/svelte/components/Textarea.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { modelValue, placeholder, disabled, readonly, id, name, rows = 3, error = false, class: className, ...restProps }: {
  modelValue?: string;
  placeholder?: string;
  disabled?: boolean;
  readonly?: boolean;
  id?: string;
  name?: string;
  rows?: number;
  error?: boolean;
    class?: string;
    [key: string]: any;
  } = $props();




const emit = defineEmits<{
  "update:modelValue": [value: string];
  change: [event: Event];
  blur: [event: FocusEvent];
  focus: [event: FocusEvent];
}>();

let classes = $derived(
cn(
    "flex min-h-[80px] w-full rounded-[--la-radius] border bg-[hsl(var(--la-background))] px-3 py-2 text-sm text-[hsl(var(--la-foreground))] placeholder:text-[hsl(var(--la-muted-foreground))] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 resize-none",
    error
      ? "border-[hsl(var(--la-destructive))] focus-visible:ring-[hsl(var(--la-destructive))]"
      : "border-[hsl(var(--la-input))] focus-visible:ring-[hsl(var(--la-ring))]",
    className,
  ),
);
</script>

<textarea
    id={id}
    :name="name"
    :placeholder="placeholder"
    disabled={disabled}
    :readonly="readonly"
    :rows="rows"
    class={classes}
    value={modelValue}
    @input="emit('update:modelValue', ($event.target as HTMLTextAreaElement).value)"
    @change="emit('change', $event)"
    @blur="emit('blur', $event as FocusEvent)"
    @focus="emit('focus', $event as FocusEvent)"
  / {...restProps}>

// src/components/Textarea/Textarea.tsx
import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";
import { cn } from "../../lib/utils";

const textareaVariants = cva(
  "flex w-full rounded-md border bg-background text-foreground text-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
  {
    variants: {
      resize: {
        none: "resize-none",
        vertical: "resize-y",
        horizontal: "resize-x",
        both: "resize",
      },
      error: {
        true: "border-destructive focus-visible:ring-destructive",
        false: "border-input",
      },
    },
    defaultVariants: {
      resize: "vertical",
      error: false,
    },
  },
);

export interface TextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement>,
    VariantProps<typeof textareaVariants> {
  error?: boolean;
}

function Textarea({
  className,
  resize,
  error,
  rows = 3,
  ref,
  ...props
}: TextareaProps & { ref?: React.Ref<HTMLTextAreaElement> }) {
  if (
    process.env.NODE_ENV !== "production" &&
    !props.id &&
    !props["aria-label"] &&
    !props["aria-labelledby"]
  ) {
    console.warn(
      "Textarea: missing label association. Provide `id` paired with a <Label htmlFor>, or pass `aria-label`/`aria-labelledby`.",
    );
  }
  return (
    <textarea
      ref={ref}
      rows={rows}
      className={cn(
        textareaVariants({ resize, error }),
        "px-4 py-4 md:px-3 md:py-2 text-base md:text-sm",
        className,
      )}
      aria-invalid={error || undefined}
      {...props}
    />
  );
}

Textarea.displayName = "Textarea";

export type TextareaVariants = VariantProps<typeof textareaVariants>;

export { Textarea };
