// src/components/Avatar/Avatar.tsx
import * as AvatarPrimitive from "@radix-ui/react-avatar";
import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";
import { cn } from "../../lib/utils";

const avatarVariants = cva(
  "relative flex shrink-0 overflow-hidden rounded-full",
  {
    variants: {
      size: {
        sm: "h-8 w-8",
        md: "h-10 w-10",
        lg: "h-14 w-14",
      },
    },
    defaultVariants: {
      size: "md",
    },
  },
);

export interface AvatarProps
  extends React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Root>,
    VariantProps<typeof avatarVariants> {}

function Avatar({
  className,
  size,
  ref,
  ...props
}: AvatarProps & {
  ref?: React.Ref<React.ComponentRef<typeof AvatarPrimitive.Root>>;
}) {
  return (
    <AvatarPrimitive.Root
      ref={ref}
      className={cn(avatarVariants({ size }), className)}
      {...props}
    />
  );
}
Avatar.displayName = AvatarPrimitive.Root.displayName;

export interface AvatarImageProps
  extends React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Image> {
  alt: string;
}

function AvatarImage({
  className,
  alt,
  ref,
  ...props
}: AvatarImageProps & {
  ref?: React.Ref<React.ComponentRef<typeof AvatarPrimitive.Image>>;
}) {
  if (process.env.NODE_ENV !== "production" && !alt) {
    console.warn(
      "AvatarImage: `alt` prop is required for WCAG 1.1.1 compliance.",
    );
  }
  return (
    <AvatarPrimitive.Image
      ref={ref}
      alt={alt}
      className={cn("aspect-square h-full w-full object-cover", className)}
      {...props}
    />
  );
}
AvatarImage.displayName = AvatarPrimitive.Image.displayName;

function AvatarFallback({
  className,
  ref,
  ...props
}: React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Fallback> & {
  ref?: React.Ref<React.ComponentRef<typeof AvatarPrimitive.Fallback>>;
}) {
  return (
    <AvatarPrimitive.Fallback
      ref={ref}
      className={cn(
        "flex h-full w-full items-center justify-center rounded-full bg-muted text-muted-foreground text-sm font-medium",
        className,
      )}
      {...props}
    />
  );
}
AvatarFallback.displayName = AvatarPrimitive.Fallback.displayName;

export type AvatarVariants = VariantProps<typeof avatarVariants>;

export { Avatar, AvatarFallback, AvatarImage };

// src/svelte/components/Avatar.svelte
<script lang="ts">
import { computed, ref } from "vue";
import { cn } from "../utils/cn";

  let { src, alt, fallback, size = "md", class: className, ...restProps }: {
  src?: string;
  alt?: string;
  fallback?: string;
  size?: "sm" | "md" | "lg" | "xl";
    class?: string;
    [key: string]: any;
  } = $props();




const imgError = ref(false);

const sizeClasses = {
  sm: "h-8 w-8 text-xs",
  md: "h-10 w-10 text-sm",
  lg: "h-12 w-12 text-base",
  xl: "h-16 w-16 text-lg",
};

let classes = $derived(
cn(
    "relative flex shrink-0 overflow-hidden rounded-full",
    sizeClasses[size],
    className,
  ),
);

const initials = computed(() => {
  if (fallback) return fallback.slice(0, 2).toUpperCase();
  if (alt) {
    return alt
      .split(" ")
      .map((w) => w[0])
      .slice(0, 2)
      .join("")
      .toUpperCase();
  }
  return "?";
});
</script>

<span class={classes} {...restProps}>
    <img
      v-if="src && !imgError"
      :src="src"
      :alt="alt ?? ''"
      class="aspect-square h-full w-full object-cover"
      @error="imgError = true"
    />
    <span
      v-else
      class="flex h-full w-full items-center justify-center rounded-full bg-[hsl(var(--la-muted))] font-medium text-[hsl(var(--la-muted-foreground))]"
    >
      <slot>{{ initials }}</slot>
    </span>
  </span>
