// src/components/Checkbox/Checkbox.tsx
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";
import { cn } from "../../lib/utils";

const checkboxVariants = cva(
  "peer shrink-0 rounded-sm border border-primary ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground data-[state=indeterminate]:bg-primary data-[state=indeterminate]:text-primary-foreground",
  {
    variants: {
      size: {
        sm: "h-5 w-5 md:h-3.5 md:w-3.5 min-h-[44px] min-w-[44px] md:min-h-0 md:min-w-0 p-2.5 md:p-0",
        md: "h-6 w-6 md:h-4 md:w-4 min-h-[44px] min-w-[44px] md:min-h-0 md:min-w-0 p-2.5 md:p-0",
        lg: "h-6 w-6 min-h-[44px] min-w-[44px] p-2.5",
      },
    },
    defaultVariants: {
      size: "md",
    },
  },
);

export interface CheckboxProps
  extends React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>,
    VariantProps<typeof checkboxVariants> {}

function Checkbox({
  className,
  size,
  ref,
  ...props
}: CheckboxProps & {
  ref?: React.Ref<React.ComponentRef<typeof CheckboxPrimitive.Root>>;
}) {
  return (
    <CheckboxPrimitive.Root
      ref={ref}
      className={cn(checkboxVariants({ size }), className)}
      {...props}
    >
      <CheckboxPrimitive.Indicator className="group flex items-center justify-center text-current">
        <svg
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          className={cn(
            "group-data-[state=indeterminate]:hidden",
            size === "sm"
              ? "h-3 w-3 md:h-3 md:w-3"
              : size === "lg"
                ? "h-3.5 w-3.5"
                : "h-3 w-3 md:h-3 md:w-3",
          )}
        >
          <polyline points="20 6 9 17 4 12" />
        </svg>
        <svg
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="3"
          strokeLinecap="round"
          className={cn(
            "group-data-[state=checked]:hidden",
            size === "sm"
              ? "h-3 w-3 md:h-3 md:w-3"
              : size === "lg"
                ? "h-3.5 w-3.5"
                : "h-3 w-3 md:h-3 md:w-3",
          )}
        >
          <line x1="5" y1="12" x2="19" y2="12" />
        </svg>
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  );
}

Checkbox.displayName = CheckboxPrimitive.Root.displayName;

export type CheckboxVariants = VariantProps<typeof checkboxVariants>;

export { Checkbox };

// src/svelte/components/Checkbox.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { modelValue = false, disabled = false, id, name, value, indeterminate = false, class: className, ...restProps }: {
  modelValue?: boolean;
  disabled?: boolean;
  id?: string;
  name?: string;
  value?: string;
  indeterminate?: boolean;
    class?: string;
    [key: string]: any;
  } = $props();




const emit = defineEmits<{
  "update:modelValue": [value: boolean];
  change: [value: boolean];
}>();

let classes = $derived(
cn(
    "peer h-4 w-4 shrink-0 rounded-sm border border-[hsl(var(--la-primary))] ring-offset-[hsl(var(--la-background))] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--la-ring))] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
    modelValue || indeterminate
      ? "bg-[hsl(var(--la-primary))] text-[hsl(var(--la-primary-foreground))]"
      : "bg-[hsl(var(--la-background))]",
    className,
  ),
);

function handleChange(e: Event) {
  const checked = (e.target as HTMLInputElement).checked;
  emit("update:modelValue", checked);
  emit("change", checked);
}
</script>

<div class="relative flex items-center" {...restProps}>
    <input
      id={id}
      :name="name"
      value={value}
      type="checkbox"
      :checked="modelValue"
      disabled={disabled}
      :indeterminate="indeterminate"
      :class="cn('sr-only', classes)"
      @change="handleChange"
    />
    <div
      class={classes}
      role="presentation"
      aria-hidden="true"
    >
      <svg
        v-if="modelValue && !indeterminate"
        class="h-3 w-3"
        viewBox="0 0 12 12"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M2 6l3 3 5-5"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
      <svg
        v-else-if="indeterminate"
        class="h-3 w-3"
        viewBox="0 0 12 12"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path d="M2 6h8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
      </svg>
    </div>
  </div>
