// src/components/Label/Label.tsx
import * as LabelPrimitive from "@radix-ui/react-label";
import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";
import { cn } from "../../lib/utils";

const labelVariants = cva(
  "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
);

export interface LabelProps
  extends React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>,
    VariantProps<typeof labelVariants> {}

function Label({
  className,
  ref,
  ...props
}: LabelProps & {
  ref?: React.Ref<React.ComponentRef<typeof LabelPrimitive.Root>>;
}) {
  return (
    <LabelPrimitive.Root
      ref={ref}
      className={cn(labelVariants(), className)}
      {...props}
    />
  );
}

Label.displayName = LabelPrimitive.Root.displayName;

export type LabelVariants = VariantProps<typeof labelVariants>;

export { Label };

// src/svelte/components/Label.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { for: htmlFor, class: className, children, ...restProps }: {
  for?: string;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();

let classes = $derived(
cn("text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70", className),
);
</script>

<label for={htmlFor} class={classes} {...restProps}>
    {@render children?.()}
  </label>
