// src/svelte/components/Toggle.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { modelValue = false, variant = "default", size = "md", disabled = false, class: className, children, ...restProps }: {
  modelValue?: boolean;
  variant?: "default" | "outline";
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();




const emit = defineEmits<{
  "update:modelValue": [value: boolean];
}>();

const variantClasses = {
  default: "bg-transparent hover:bg-[hsl(var(--la-muted))] hover:text-[hsl(var(--la-muted-foreground))] data-[state=on]:bg-[hsl(var(--la-accent))] data-[state=on]:text-[hsl(var(--la-accent-foreground))]",
  outline: "border border-[hsl(var(--la-input))] bg-transparent hover:bg-[hsl(var(--la-accent))] hover:text-[hsl(var(--la-accent-foreground))] data-[state=on]:bg-[hsl(var(--la-accent))] data-[state=on]:text-[hsl(var(--la-accent-foreground))]",
};

const sizeClasses = {
  sm: "h-9 px-2.5",
  md: "h-10 px-3",
  lg: "h-11 px-5",
};

let classes = $derived(
cn(
    "inline-flex items-center justify-center rounded-[--la-radius] text-sm font-medium ring-offset-[hsl(var(--la-background))] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--la-ring))] focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
    variantClasses[variant],
    sizeClasses[size],
    className,
  ),
);

function toggle() {
  emit("update:modelValue", !modelValue);
}
</script>

<button
    type="button"
    :aria-pressed="modelValue"
    :data-state="modelValue ? 'on' : 'off'"
    disabled={disabled}
    class={classes}
    @click="toggle"
   {...restProps}>
    {@render children?.()}
  </button>

// src/components/Toggle/Toggle.tsx
import * as TogglePrimitive from "@radix-ui/react-toggle";
import { cva, type VariantProps } from "class-variance-authority";
import * as React from "react";
import { cn } from "../../lib/utils";

const toggleVariants = cva(
  "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors hover:bg-muted hover:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=on]:bg-accent data-[state=on]:text-accent-foreground",
  {
    variants: {
      variant: {
        default: "bg-transparent",
        outline:
          "border border-input bg-transparent hover:bg-accent hover:text-accent-foreground",
      },
      size: {
        sm: "h-11 md:h-9 px-3 md:px-2.5 text-sm min-h-[44px] md:min-h-0",
        md: "h-12 md:h-10 px-4 md:px-3 text-sm min-h-[44px] md:min-h-0",
        lg: "h-12 px-6 md:px-5 text-base min-h-[44px]",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "md",
    },
  },
);

export interface ToggleProps
  extends React.ComponentPropsWithoutRef<typeof TogglePrimitive.Root>,
    VariantProps<typeof toggleVariants> {}

const Toggle = React.forwardRef<
  React.ComponentRef<typeof TogglePrimitive.Root>,
  ToggleProps
>(({ className, variant, size, ...props }, ref) => (
  <TogglePrimitive.Root
    ref={ref}
    className={cn(toggleVariants({ variant, size }), className)}
    {...props}
  />
));

Toggle.displayName = TogglePrimitive.Root.displayName;

export type ToggleVariants = VariantProps<typeof toggleVariants>;

export { Toggle, toggleVariants };
